In [39]:
import pandas as pd 
import numpy as nm 
import pandas_profiling as pp

In [40]:
df = pd.read_csv('final_dataset/MD4.csv')
df.reset_index(drop=True)
df.drop(columns = df.columns[0], axis = 1, inplace= True)
df.dropna()


prov_name prov_code  area (kmq)  high_hydraulic_risk_area_p3 (%)  \
0       Piacenza        PC    2585.765                            7.111   
1          Parma        PR    3447.400                           10.092   
2  Reggio Emilia        RE    2291.145                            5.977   
3         Modena        MO    2687.882                            6.118   
4        Bologna        BO    3702.249                           13.417   
5        Ferrara        FE    2627.377                           23.908   
6        Ravenna        RA    1859.392                           22.243   
7   Forlì-Cesena        FC    2378.318                            6.239   
8         Rimini        RN     865.014                            9.203   

   medium_hydraulic_risk_area_p2 (%)  low_hydraulic_risk_area_p1 (%)  \
0                             23.284                          24.885   
1                             25.140                          27.911   
2                             46.257                          50.943   
3                             41.264                          45.580   
4                             50.047                          50.254   
5                             99.904                          99.909   
6                             79.949                          79.954   
7                             20.564                          20.591   
8                             16.694                          18.239   

   very_high_landslide_risk_area_p4 (%)  high_landslide_risk_area_p3 (%)  \
0                                 3.876                           13.674   
1                                 6.228                           11.544   
2                                 5.896                            7.913   
3                                 3.222                           10.251   
4                                 0.925                           12.067   
5                                 0.000                            0.000   
6                                 1.528                            4.981   
7                                16.314                           14.572   
8                                10.825                           10.990   

   medium_landslide_risk_area_p2 (%)  low_landslide_risk_area_p1 (%)  ...  \
0                              0.185                           0.000  ...   
1                              3.036                           0.001  ...   
2                              0.137                           0.007  ...   
3                              1.859                           0.163  ...   
4                              0.569                           2.339  ...   
5                              0.000                           0.000  ...   
6                              0.400                           0.206  ...   
7                              4.803                           2.731  ...   
8                              0.130                           0.005  ...   

   attention_enterprise (%)  cultural_heritage (n)  \
0                     0.000                   2251   
1                     0.000                   2654   
2                     0.000                   4074   
3                     0.047                   1812   
4                     4.687                   3923   
5                     0.000                   2519   
6                     0.159                   2191   
7                     0.000                   1843   
8                     0.000                   1178   

   high_hydraulic_risk_cultural_heritage_p3 (%)  \
0                                         3.554   
1                                        12.773   
2                                         6.873   
3                                         6.236   
4                                         9.865   
5                                        11.473   
6                                         8.352   
7                                         9.278   
8  

In [41]:
set(df.prov_name)

{'Bologna',
 'Ferrara',
 'Forlì-Cesena',
 'Modena',
 'Parma',
 'Piacenza',
 'Ravenna',
 'Reggio Emilia',
 'Rimini'}

# 1. Financing line chart (MD1) - provinces 

In [65]:
df = pd.read_csv('./final_dataset/MD1.csv')
df = df.drop(['Unnamed: 0'], axis=1)
df['date'] = df['date'].apply(lambda x: x.split('/')[2])
df =df[df['date'] != 'nan']
df['tot_action_financing']= df['tot_action_financing'].astype('str')
df['tot_action_financing']= df['tot_action_financing'].apply(lambda x: x.split(','))
df['tot_action_financing']= df['tot_action_financing'].apply(lambda x: '.'.join(x))
df['tot_action_financing']= df['tot_action_financing'].astype('float64')
df =df[df['tot_action_financing'] != 'NaN']
df = df.groupby(['prov_name', 'prov_code', 'date'], as_index=False).sum('tot_action_financing')
df = df.sort_values(by="date")
df


prov_name prov_code  date     latitude   longitude  \
0          Bologna        BO  1996    44.353074   11.714156   
122        Ravenna        RA  1996    44.417225   12.199139   
81           Parma        PR  1999  1028.359865  230.569877   
123        Ravenna        RA  1999  1151.107749  307.566162   
61          Modena        MO  1999  1994.300864  486.550866   
..             ...       ...   ...          ...         ...   
141        Ravenna        RA  2022   399.933211  109.475271   
40         Ferrara        FE  2022   537.422883  139.678631   
161  Reggio Emilia        RE  2022   715.407712  170.168119   
60    Forlì-Cesena        FC  2022   529.877633  145.976972   
182         Rimini        RN  2022   484.232632  138.379790   

     tot_action_financing  
0              3000000.00  
122            1435306.30  
81             4622289.24  
123            2272410.36  
61             5482813.09  
..                    ...  
141             489169.01  
40              855717.26  
161            1577147.16  
60              885197.54  
182             911397.29  

[183 rows x 6 columns]

In [66]:
df.tot_action_financing.sum()

5098356716.49

In [43]:
sub = df[df.prov_name == 'Bologna'].reset_index(drop=True)
sub['date'] = sub['date'].astype(int)
sub = sub[(sub.date>=2002) & (sub.date <= 2021)]
sub.reset_index(drop=True)
sub.tot_action_financing.values

array([2.85177826e+07, 4.15000000e+07, 3.06649490e+07, 2.66200000e+06,
       3.96000000e+06, 2.89019917e+07, 9.54350550e+07, 2.18282807e+08,
       2.10403095e+08, 7.69794208e+07, 7.26440130e+07, 9.84902316e+07,
       8.13473205e+07, 1.50193757e+08, 1.26029993e+08, 2.29355658e+08,
       1.66281925e+08, 1.10385626e+08, 1.25514942e+08, 9.16943960e+07])

In [44]:
modena = df[df.prov_name == 'Modena'].reset_index(drop=True)
modena['date'] = modena['date'].astype(int)
modena = modena[(modena.date>=2002) & (modena.date <= 2021)]
modena.loc[len(modena)+1] = ['Modena', 'MO', 2003, 0, 0, 0]
modena.loc[len(modena)+2] = ['Modena', 'MO', 2004, 0, 0, 0]
modena = modena.sort_values(by="date").reset_index(drop=True)
modena.tot_action_financing.values

array([ 1084559.49,        0.  ,        0.  ,   400000.  ,   658600.  ,
       11037222.74, 11380524.21, 35204576.08, 29287034.97,  8469372.34,
       21856183.72, 34847310.98, 19401867.24, 32552589.17, 75252312.78,
       41425812.45, 44230528.95, 41746481.37, 57971032.87, 26982286.77])

In [45]:
ferrara = df[df.prov_name == 'Ferrara'].reset_index(drop=True)
ferrara['date'] = ferrara['date'].astype(int)
ferrara = ferrara[(ferrara.date>=2002) & (ferrara.date <= 2021)]
ferrara.loc[len(ferrara)+1] = ['Ferrara', 'FE', 2002, 0, 0, 0]
ferrara.loc[len(ferrara)+2] = ['Ferrara', 'FE', 2003, 0, 0, 0]
ferrara.loc[len(ferrara)+3] = ['Ferrara', 'FE', 2004, 0, 0, 0]
ferrara.loc[len(ferrara)+4] = ['Ferrara', 'FE', 2005, 0, 0, 0]
ferrara.loc[len(ferrara)+6] = ['Ferrara', 'FE', 2006, 0, 0, 0]
ferrara = ferrara.sort_values(by="date").reset_index(drop=True)
ferrara.tot_action_financing.values

array([       0.  ,        0.  ,        0.  ,        0.  ,        0.  ,
        4231670.55,  9773041.54, 19395406.2 , 36514783.19, 14948755.89,
        5925099.11, 10012497.  , 14984965.8 , 30241281.74, 49942968.51,
       30712033.61, 18616359.55, 22168686.26, 22582511.33, 15401565.74])

In [46]:
forli_cesena = df[df.prov_name == 'Forlì-Cesena'].reset_index(drop=True)
forli_cesena['date'] = forli_cesena['date'].astype(int)
forli_cesena = forli_cesena[(forli_cesena.date>=2002) & (forli_cesena.date <= 2021)]
forli_cesena.loc[len(forli_cesena)+1] = ['Forlì-Cesena', 'FC', 2003, 0, 0, 0]
forli_cesena.loc[len(forli_cesena)+2] = ['Forlì-Cesena', 'FC', 2004, 0, 0, 0]
forli_cesena = forli_cesena.sort_values(by="date").reset_index(drop=True)
forli_cesena.tot_action_financing.values

array([ 1527976.73,        0.  ,        0.  ,  2373000.  ,  3008600.  ,
        8001304.81,  8418660.92, 14990082.82, 32393062.67, 14179905.96,
       15249619.96, 11149787.99,  6949342.47, 19626904.19, 41285001.84,
       23239100.59, 26589379.06, 19246743.39, 16170932.43, 19294181.69])

In [47]:
parma = df[df.prov_name == 'Parma'].reset_index(drop=True)
parma['date'] = parma['date'].astype(int)
parma = parma[(parma.date>=2002) & (parma.date <= 2021)]
parma.loc[len(parma)+1] = ['Parma', 'PR', 2003, 0, 0, 0]
parma.loc[len(parma)+2] = ['Parma', 'PR', 2005, 0, 0, 0]
parma = parma.sort_values(by="date").reset_index(drop=True)
parma.tot_action_financing.values

array([ 9521538.84,        0.  ,  9996600.  ,        0.  ,  5150000.  ,
       13888677.27, 18487330.98, 17202572.4 , 28654806.16, 16685313.1 ,
        8832395.26, 12215418.7 ,  4831124.4 , 26887851.59, 57485838.63,
       37805906.25, 81259762.43, 30998172.02, 44395106.39, 19530454.42])

In [48]:
piacenza = df[df.prov_name == 'Piacenza'].reset_index(drop=True)
piacenza['date'] = piacenza['date'].astype(int)
piacenza = piacenza[(piacenza.date>=2002) & (piacenza.date <= 2021)]
piacenza.loc[len(piacenza)+1] = ['Piacenza', 'PC', 2003, 0, 0, 0]
piacenza = piacenza.sort_values(by="date").reset_index(drop=True)
piacenza.tot_action_financing.values

array([2.78886726e+06, 0.00000000e+00, 1.00000000e+06, 9.00000000e+05,
       3.20061309e+06, 5.23454919e+06, 1.60378146e+07, 2.34326682e+07,
       3.39327289e+07, 1.60977396e+07, 1.10046216e+07, 1.08669678e+07,
       4.40952353e+06, 3.23400474e+07, 4.70991283e+07, 1.01179022e+08,
       3.42682986e+07, 2.20544587e+07, 2.96477040e+07, 1.80307608e+07])

In [49]:
rimini = df[df.prov_name == 'Rimini'].reset_index(drop=True)
rimini['date'] = rimini['date'].astype(int)
rimini = rimini[(rimini.date>=2002) & (rimini.date <= 2021)]
rimini.loc[len(rimini)+1] = ['Rimini', 'RN', 2003, 0, 0, 0]
rimini = rimini.sort_values(by="date").reset_index(drop=True)
rimini.tot_action_financing.values

array([ 5109297.41,        0.  ,  2000000.  ,  1754281.  ,  1743000.  ,
       13507120.87,  9884436.83, 11425099.25, 25750616.56, 10408982.25,
       10257944.07, 11541697.92, 35229290.11, 20925667.8 , 33801820.52,
       55265183.11, 45530857.13, 34526924.18,  8363784.6 , 15069892.59])

In [50]:
ravenna = df[df.prov_name == 'Ravenna'].reset_index(drop=True)
ravenna['date'] = ravenna['date'].astype(int)
ravenna = ravenna[(ravenna.date>=2002) & (ravenna.date <= 2021)]
ravenna = ravenna.sort_values(by="date").reset_index(drop=True)
ravenna.loc[len(ravenna)+1] = ['Ravenna', 'RA', 2003, 0, 0, 0]
ravenna.loc[len(ravenna)+2] = ['Ravenna', 'RA', 2004, 0, 0, 0]
ravenna.loc[len(ravenna)+3] = ['Ravenna', 'RA', 2006, 0, 0, 0]
ravenna = ravenna.sort_values(by="date").reset_index(drop=True)
ravenna.tot_action_financing.values

array([2.46371126e+06, 0.00000000e+00, 0.00000000e+00, 3.50000000e+04,
       0.00000000e+00, 7.65557800e+06, 1.12184967e+07, 1.60226271e+07,
       3.05743612e+07, 9.79108572e+06, 1.18922252e+07, 1.73383396e+07,
       6.49951286e+06, 1.74740376e+07, 5.26963954e+07, 3.89779793e+07,
       2.48532802e+07, 1.61235898e+07, 6.54452857e+07, 1.49206940e+07])

In [51]:
reggioemilia = df[df.prov_name == 'Reggio Emilia'].reset_index(drop=True)
reggioemilia['date'] = reggioemilia['date'].astype(int)
reggioemilia = reggioemilia[(reggioemilia.date>=2002) & (reggioemilia.date <= 2021)]
reggioemilia = reggioemilia.sort_values(by="date").reset_index(drop=True)
reggioemilia.loc[len(reggioemilia)+1] = ['Reggio Emilia', 'RE', 2003, 0, 0, 0]
reggioemilia.loc[len(reggioemilia)+2] = ['Reggio Emilia', 'RE', 2004, 0, 0, 0]
reggioemilia.loc[len(reggioemilia)+3] = ['Reggio Emilia', 'RE', 2005, 0, 0, 0]
reggioemilia = reggioemilia.sort_values(by="date").reset_index(drop=True)
reggioemilia.tot_action_financing.values

array([ 2036205.18,        0.  ,        0.  ,        0.  ,  4345915.68,
        8012668.77, 19629226.79, 48884116.3 , 21920274.09, 11556428.36,
       14275137.25, 25391040.06,  7835046.21, 22882087.07, 63333588.09,
       57952931.15, 25371891.36, 23728830.12, 28413815.41, 19245123.36])

# 2. Financing bar chart (MD1) - provinces 

In [71]:
df2 = pd.read_csv('./final_dataset/MD1.csv')
df2 = df2.drop(['Unnamed: 0'], axis=1)
df2['tot_action_financing']= df2['tot_action_financing'].astype('str')
df2['tot_action_financing']= df2['tot_action_financing'].apply(lambda x: x.split(','))
df2['tot_action_financing']= df2['tot_action_financing'].apply(lambda x: '.'.join(x))
df2['tot_action_financing']= df2['tot_action_financing'].astype('float64')
df2 =df2[df2['tot_action_financing'] != 'NaN']
df2 = df2.groupby(['prov_name', 'prov_code', 'action_type'], as_index=False).sum('tot_action_financing')
df2 = df2.sort_values(by="prov_name")
df2

prov_name prov_code              action_type       latitude  \
0         Bologna        BO      preventive measures  468175.059047   
1         Bologna        BO  reparatory intervention   13919.395132   
2         Ferrara        FE      preventive measures  174198.484131   
3         Ferrara        FE  reparatory intervention    1299.255808   
4    Forlì-Cesena        FC      preventive measures  175570.775518   
5    Forlì-Cesena        FC  reparatory intervention    7882.252982   
6          Modena        MO      preventive measures  296968.661997   
7          Modena        MO  reparatory intervention    5456.724839   
9           Parma        PR  reparatory intervention    6264.216684   
8           Parma        PR      preventive measures  148614.237150   
10       Piacenza        PC      preventive measures  159262.828076   
11       Piacenza        PC  reparatory intervention    9453.877021   
12        Ravenna        RA      preventive measures  201154.499698   
13        Ravenna        RA  reparatory intervention    3725.101354   
14  Reggio Emilia        RE      preventive measures   97562.991441   
15  Reggio Emilia        RE  reparatory intervention    4051.863012   
16         Rimini        RN      preventive measures  163106.151320   
17         Rimini        RN  reparatory intervention    7120.303499   

        longitude  tot_action_financing  
0   119552.035401          1.923157e+09  
1     3535.047982          1.011151e+08  
2    45340.625972          2.499887e+08  
3      340.979664          5.638143e+07  
4    48350.268925          2.483070e+08  
5     2170.372863          4.031565e+07  
6    72658.359811          4.648135e+08  
7     1326.765449          3.752266e+07  
9     1413.591807          1.199072e+08  
8    34031.323151          3.297571e+08  
10   34149.257656          3.703573e+08  
11    2015.334652          4.751908e+07  
12   54775.463864          3.127353e+08  
13    1002.264053          3.588970e+07  
14   23172.116349          3.825708e+08  
15     962.673497          3.192376e+07  
16   46558.821110          3.064678e+08  
17    2013.524678          4.711104e+07

In [73]:
preventive = df2[df2.action_type == 'preventive measures']
preventive['prov_name'].values, preventive['tot_action_financing'].values

(array(['Bologna', 'Ferrara', 'Forlì-Cesena', 'Modena', 'Parma',
        'Piacenza', 'Ravenna', 'Reggio Emilia', 'Rimini'], dtype=object),
 array([1.92315691e+09, 2.49988718e+08, 2.48306967e+08, 4.64813494e+08,
        3.29757098e+08, 3.70357333e+08, 3.12735264e+08, 3.82570784e+08,
        3.06467836e+08]))

In [74]:
reparatory = df2[df2.action_type != 'preventive measures']
reparatory['prov_name'].values, reparatory['tot_action_financing'].values

(array(['Bologna', 'Ferrara', 'Forlì-Cesena', 'Modena', 'Parma',
        'Piacenza', 'Ravenna', 'Reggio Emilia', 'Rimini'], dtype=object),
 array([1.01115056e+08, 5.63814256e+07, 4.03156537e+07, 3.75226643e+07,
        1.19907178e+08, 4.75190759e+07, 3.58897010e+07, 3.19237634e+07,
        4.71110397e+07]))

# 3. Financing suburst chart per action (MD1) - provinces 

In [75]:
df.tot_action_financing.sum()

5105839965.66

In [76]:
bologna = df2[df2.prov_name == 'Bologna'].reset_index(drop=True)
bologna.tot_action_financing.sum()


2024271969.91

In [81]:
modena = df2[df2.prov_name == 'Modena'].reset_index(drop=True)
modena.tot_action_financing.sum()


502336158.26

In [82]:
ferrara = df2[df2.prov_name == 'Ferrara'].reset_index(drop=True)
ferrara.tot_action_financing.sum()

306370143.28000003

In [83]:
forli_cesena = df2[df2.prov_name == 'Forlì-Cesena'].reset_index(drop=True)
forli_cesena.tot_action_financing.sum()

288622621.01

In [84]:
parma = df2[df2.prov_name == 'Parma'].reset_index(drop=True)
parma.tot_action_financing.sum()

449664275.59999996

In [85]:
piacenza = df2[df2.prov_name == 'Piacenza'].reset_index(drop=True)
piacenza.tot_action_financing.sum()

417876409.12

In [86]:
rimini= df2[df2.prov_name == 'Rimini'].reset_index(drop=True)
rimini.tot_action_financing.sum()

353578875.41

In [87]:
ravenna= df2[df2.prov_name == 'Ravenna'].reset_index(drop=True)
ravenna.tot_action_financing.sum()

348624965.31

In [88]:
reggioemilia = df2[df2.prov_name == 'Reggio Emilia'].reset_index(drop=True)
reggioemilia.tot_action_financing.sum()

414494547.76

In [112]:
df3 = pd.read_csv('./final_dataset/MD1.csv')
df3 = df3.drop(['Unnamed: 0'], axis=1)
df3['tot_action_financing']= df3['tot_action_financing'].astype('str')
df3['tot_action_financing']= df3['tot_action_financing'].apply(lambda x: x.split(','))
df3['tot_action_financing']= df3['tot_action_financing'].apply(lambda x: '.'.join(x))
df3['tot_action_financing']= df3['tot_action_financing'].astype('float64')
df3 =df3[df3['tot_action_financing'] != 'NaN']
df3 = df3.groupby(['prov_name', 'prov_code', 'action_description'], as_index=False).sum('tot_action_financing')
df3 = df3.sort_values(by="prov_name")
df3

prov_name prov_code                                 action_description  \
0      Bologna        BO  Actions for raising the quality of life in urb...   
106    Bologna        BO                       Parking and exchange systems   
107    Bologna        BO                 Parks and reserves protected areas   
108    Bologna        BO  Permanent training professional and technical ...   
109    Bologna        BO        Plants and machinery for trade and services   
...        ...       ...                                                ...   
1090    Rimini        RN     IFTS (Higher Technical Education and Training)   
1089    Rimini        RN  IFTS (Higher Technical Education and Training ...   
1088    Rimini        RN                                             Hotels   
1102    Rimini        RN                                      Kindergartens   
1186    Rimini        RN                                          Waterways   

          latitude    longitude  tot_action_financing  
0       177.977467    45.366883             233035.82  
106      44.494367    11.341721             200000.00  
107      44.492238    11.218183            1188000.00  
108   20068.753251  5116.044615            4982114.60  
109     223.152543    55.876962           49026840.52  
...            ...          ...                   ...  
1090    881.218017   251.312590            2652746.00  
1089    220.304504    62.828148             602150.00  
1088   1056.100037   303.339273            3158589.84  
1102    308.048219    87.701120             395483.80  
1186    131.964457    37.912649             653702.80  

[1187 rows x 6 columns]

In [98]:
categories = {'Beaches', 'Coastal', 'Contaminated and/or degraded sites', 'Control and protection of the Earth and Marino environment',
 'Cragical defense', 'Defense port area', 'Detached longitudinal defense', 'Environmental safeguarding technologies',
'Flood', 'Fluvia infrastructures/infrastructures/infrastructures/structures',  'Landslide', 'Port area', 'Water adjustment', 'Waterways', 'Urban water networks',}

In [110]:
bologna3 = df3[df3.prov_name == 'Bologna'].reset_index(drop=True)
tot_fin= 0
for cat in categories:
    support = bologna3[bologna3.action_description == cat]
    tot_fin+=support.tot_action_financing.sum()
    print(cat, support.tot_action_financing.sum())


others = bologna3.tot_action_financing.sum()-tot_fin
print('others=', others)

Cragical defense 0.0
Environmental safeguarding technologies 11831375.68
Urban water networks 1430000.0
Detached longitudinal defense 0.0
Contaminated and/or degraded sites 3364855.0
Coastal 0.0
Defense port area 0.0
Control and protection of the Earth and Marino environment 22380.68
Fluvia infrastructures/infrastructures/infrastructures/structures 0.0
Water adjustment 26002685.0
Waterways 1135091.3599999999
Port area 0.0
Beaches 0.0
Landslide 15187218.44
Flood 80522290.32
others= 1884776073.43


In [114]:
modena3 = df3[df3.prov_name == 'Modena'].reset_index(drop=True)
tot_fin= 0
for cat in categories:
    support = modena3[modena3.action_description == cat]
    tot_fin+=support.tot_action_financing.sum()
    print(cat, support.tot_action_financing.sum())


others = modena3.tot_action_financing.sum()-tot_fin
print('others=', others)


Cragical defense 0.0
Environmental safeguarding technologies 4339314.98
Urban water networks 2189800.0
Detached longitudinal defense 0.0
Contaminated and/or degraded sites 0.0
Coastal 0.0
Defense port area 0.0
Control and protection of the Earth and Marino environment 0.0
Fluvia infrastructures/infrastructures/infrastructures/structures 0.0
Water adjustment 180118.75
Waterways 2239500.0
Port area 0.0
Beaches 0.0
Landslide 12717202.63
Flood 21796861.65
others= 458873360.25


In [115]:
ferrara3 = df3[df3.prov_name == 'Modena'].reset_index(drop=True)
tot_fin= 0
for cat in categories:
    support = ferrara3[ferrara3.action_description == cat]
    tot_fin+=support.tot_action_financing.sum()
    print(cat, support.tot_action_financing.sum())


others = ferrara3.tot_action_financing.sum()-tot_fin
print('others=', others)

Cragical defense 0.0
Environmental safeguarding technologies 4339314.98
Urban water networks 2189800.0
Detached longitudinal defense 0.0
Contaminated and/or degraded sites 0.0
Coastal 0.0
Defense port area 0.0
Control and protection of the Earth and Marino environment 0.0
Fluvia infrastructures/infrastructures/infrastructures/structures 0.0
Water adjustment 180118.75
Waterways 2239500.0
Port area 0.0
Beaches 0.0
Landslide 12717202.63
Flood 21796861.65
others= 458873360.25


In [116]:
forli_cesena = df3[df3.prov_name == 'Forlì-Cesena'].reset_index(drop=True)
tot_fin= 0
for cat in categories:
    support = forli_cesena[forli_cesena.action_description == cat]
    tot_fin+=support.tot_action_financing.sum()
    print(cat, support.tot_action_financing.sum())


others = forli_cesena.tot_action_financing.sum()-tot_fin
print('others=', others)

Cragical defense 0.0
Environmental safeguarding technologies 1186130.12
Urban water networks 800000.0
Detached longitudinal defense 0.0
Contaminated and/or degraded sites 0.0
Coastal 225855.75
Defense port area 0.0
Control and protection of the Earth and Marino environment 0.0
Fluvia infrastructures/infrastructures/infrastructures/structures 300000.0
Water adjustment 150000.0
Waterways 607914.0
Port area 0.0
Beaches 215855.75
Landslide 13626347.08
Flood 23248450.9
others= 248262067.41


In [117]:
parma3 = df3[df3.prov_name == 'Parma'].reset_index(drop=True)
tot_fin= 0
for cat in categories:
    support = parma3[parma3.action_description == cat]
    tot_fin+=support.tot_action_financing.sum()
    print(cat, support.tot_action_financing.sum())


others = parma3.tot_action_financing.sum()-tot_fin
print('others=', others)

Cragical defense 0.0
Environmental safeguarding technologies 1179898.92
Urban water networks 3206538.51
Detached longitudinal defense 0.0
Contaminated and/or degraded sites 5817142.65
Coastal 0.0
Defense port area 0.0
Control and protection of the Earth and Marino environment 0.0
Fluvia infrastructures/infrastructures/infrastructures/structures 0.0
Water adjustment 0.0
Waterways 9816100.0
Port area 0.0
Beaches 0.0
Landslide 18370147.85
Flood 99987030.23
others= 311287417.44000006


In [118]:
piacenza3 = df3[df3.prov_name == 'Piacenza'].reset_index(drop=True)
tot_fin= 0
for cat in categories:
    support = piacenza3[piacenza3.action_description == cat]
    tot_fin+=support.tot_action_financing.sum()
    print(cat, support.tot_action_financing.sum())


others = piacenza3.tot_action_financing.sum()-tot_fin
print('others=', others)

Cragical defense 0.0
Environmental safeguarding technologies 676525.37
Urban water networks 4043316.53
Detached longitudinal defense 0.0
Contaminated and/or degraded sites 0.0
Coastal 0.0
Defense port area 0.0
Control and protection of the Earth and Marino environment 0.0
Fluvia infrastructures/infrastructures/infrastructures/structures 0.0
Water adjustment 1336086.37
Waterways 135439.32
Port area 0.0
Beaches 0.0
Landslide 14050175.030000001
Flood 30518900.89
others= 367115965.61


In [123]:
rimini3= df3[df3.prov_name == 'Rimini'].reset_index(drop=True)
tot_fin= 0
for cat in categories:
    support = rimini3[rimini3.action_description == cat]
    tot_fin+=support.tot_action_financing.sum()
    print(cat, support.tot_action_financing.sum())


others = rimini3.tot_action_financing.sum()-tot_fin
print('others=', others)

Cragical defense 0.0
Environmental safeguarding technologies 1772732.1
Urban water networks 870000.0
Detached longitudinal defense 0.0
Contaminated and/or degraded sites 0.0
Coastal 8495524.7
Defense port area 0.0
Control and protection of the Earth and Marino environment 0.0
Fluvia infrastructures/infrastructures/infrastructures/structures 0.0
Water adjustment 200000.0
Waterways 653702.8
Port area 0.0
Beaches 175124.7
Landslide 12768970.27
Flood 20304063.76
others= 308338757.08000004


In [127]:
ravenna3= df3[df3.prov_name == 'Ravenna'].reset_index(drop=True)
tot_fin= 0
for cat in categories:
    support = ravenna3[ravenna3.action_description == cat]
    tot_fin+=support.tot_action_financing.sum()
    print(cat, support.tot_action_financing.sum())


others = ravenna3.tot_action_financing.sum()-tot_fin
print('others=', others)
ravenna3.tot_action_financing.sum()

Cragical defense 0.0
Environmental safeguarding technologies 3474685.75
Urban water networks 800000.0
Detached longitudinal defense 0.0
Contaminated and/or degraded sites 0.0
Coastal 0.0
Defense port area 0.0
Control and protection of the Earth and Marino environment 0.0
Fluvia infrastructures/infrastructures/infrastructures/structures 0.0
Water adjustment 2850000.0
Waterways 724464.0
Port area 0.0
Beaches 500000.0
Landslide 1436617.8800000001
Flood 33953083.12
others= 304886114.56


348624965.31

In [125]:
reggioemilia3 = df3[df3.prov_name == 'Reggio Emilia'].reset_index(drop=True)
tot_fin= 0
for cat in categories:
    support = reggioemilia3[reggioemilia3.action_description == cat]
    tot_fin+=support.tot_action_financing.sum()
    print(cat, support.tot_action_financing.sum())


others = reggioemilia3.tot_action_financing.sum()-tot_fin
print('others=', others)

Cragical defense 0.0
Environmental safeguarding technologies 4867623.59
Urban water networks 1740000.0
Detached longitudinal defense 0.0
Contaminated and/or degraded sites 0.0
Coastal 0.0
Defense port area 0.0
Control and protection of the Earth and Marino environment 0.0
Fluvia infrastructures/infrastructures/infrastructures/structures 0.0
Water adjustment 0.0
Waterways 6350000.0
Port area 0.0
Beaches 0.0
Landslide 15727261.7
Flood 14225701.74
others= 371583960.73


# 4. Disruption subburst chart per type (MD1) - provinces 

In [153]:
df4 = pd.read_csv('./final_dataset/MD2.csv')
df4 = df4.drop(['Unnamed: 0'], axis=1)
df4 = df4[df4['prov_code'] != 'missing']
df4 = df4[df4['prov_code'] != 'MN']

df4


id                                               type  \
0    Erosion-0                                      Coast erosion   
1    Erosion-1                                      Coast erosion   
2    Erosion-2                                      Coast erosion   
3    Erosion-3                                      Coast erosion   
4    Erosion-4                                      Coast erosion   
..         ...                                                ...   
514  Sign-7979                               Wells with hot water   
515  Sign-7979                               Wells with hot water   
516  Sign-7979  Gas leaks from wells for water and / or from t...   
517  Sign-7979                               Wells with hot water   
518  Sign-7979                               Wells with hot water   

      municipality prov_code     latitude    longitude       Date  
0        comacchio        FE  44.69462384  12.18387254    Unknown  
1        comacchio        FE  44.69462384  12.18387254    Unknown  
2        comacchio        FE  44.69462384  12.18387254    Unknown  
3        comacchio        FE  44.69462384  12.18387254    Unknown  
4        comacchio        FE  44.69462384  12.18387254    Unknown  
..             ...       ...          ...          ...        ...  
514  finale emilia        MO  44.83221342   11.2957332   1/1/2014  
515        medolla        MO  44.84894472  11.07147687  1/10/2017  
516        medolla        MO  44.84894472  11.07147687   1/9/2014  
517        medolla        MO  44.84894472  11.07147687  1/10/2015  
518        medolla        MO  44.84894472  11.07147687  1/10/2015  

[514 rows x 7 columns]

In [145]:
provs = set(df4.prov_code)

In [155]:
for province in provs:
    support = df4[df4.prov_code == province].values
    print(province,len(support))

RE 39
PC 55
MO 76
RN 56
BO 114
PR 42
RA 44
FC 50
FE 38


In [154]:
disruptions = set(df4.type)
disruptions

{'Coast erosion',
 'Coastal Disruption',
 'Gas leaks from wells for water and / or from the ground',
 'Idraulico',
 'Landslide',
 'Presence of fractures and / or sinking into the ground',
 'Unknown',
 'Volcanoes of mud and / or sand',
 'Wells with hot water'}

In [161]:
for province in provs:
    print(province)
    support = df4[df4.prov_code == province]
    for disruption in disruptions:
        support2 = support[support.type == disruption]
        print(disruption,len(support2))
    

RE
Unknown 0
Coastal Disruption 0
Coast erosion 0
Wells with hot water 5
Gas leaks from wells for water and / or from the ground 1
Presence of fractures and / or sinking into the ground 0
Idraulico 7
Volcanoes of mud and / or sand 4
Landslide 22
PC
Unknown 0
Coastal Disruption 0
Coast erosion 0
Wells with hot water 0
Gas leaks from wells for water and / or from the ground 0
Presence of fractures and / or sinking into the ground 0
Idraulico 32
Volcanoes of mud and / or sand 0
Landslide 23
MO
Unknown 2
Coastal Disruption 0
Coast erosion 0
Wells with hot water 30
Gas leaks from wells for water and / or from the ground 11
Presence of fractures and / or sinking into the ground 3
Idraulico 9
Volcanoes of mud and / or sand 2
Landslide 19
RN
Unknown 0
Coastal Disruption 5
Coast erosion 8
Wells with hot water 1
Gas leaks from wells for water and / or from the ground 0
Presence of fractures and / or sinking into the ground 0
Idraulico 15
Volcanoes of mud and / or sand 0
Landslide 27
BO
Unknown 1